routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', function () {
//    return view('welcome');
//});
use App\Articles;
use Illuminate\Support\Facades\Input;

Route::get('/testdb', function () {
    $test = new \App\DataResources\CategoriesData();
    $test->getAll();
});


Auth::routes();
Route::get('/', 'HomeController@index')->name('index');

Route::get('/logout', '\App\Http\Controllers\Auth\LoginController@logout');

Route::get('/submit', function () {
    return view('submit');
});

Route::prefix('admin')->middleware('auth')->group(function () {
//    return 'Hello';
    Route::get('', 'Admin\HomeController@index')->name('index');

    Route::get('article/create', 'Admin\ArticlesController@create')->name('create_article');
    Route::get('articles', 'Admin\ArticlesController@index')->name('all_articles');
    Route::get('article/{id}/edit', 'Admin\ArticlesController@edit')->name('edit_article');
    Route::patch('article/{id}', 'Admin\ArticlesController@update')->name('update_article');
    Route::get('article/{id}', 'Admin\ArticlesController@show')->name('show_article');
    Route::delete('article/{id}', 'Admin\ArticlesController@destroy')->name('destroy_article');
    Route::post('article', 'Admin\ArticlesController@store')->name('store_article');

    Route::post('category', 'Admin\CategoriesController@store')->name('store_category');
    Route::get('categories', 'Admin\CategoriesController@index')->name('categories');
    Route::get('category/create', 'Admin\CategoriesController@create')->name('create_category');
    Route::get('category/{id}/edit', 'Admin\CategoriesController@edit')->name('edit_category');
    Route::patch('category/{id}', 'Admin\CategoriesController@update')->name('update_category');
    Route::delete('category/{id}', 'Admin\CategoriesController@destroy')->name('destroy_category');

    Route::get('article/{id}/{slug?}', 'ArticleController@detail');

    Route::delete('img/{gallery}', 'Admin\GalleryController@destroy')->name('destroy_image');
});

Route::resource('articles', 'ArticleController');
Route::get('categories',['uses'=>'CategoryController@manageCategory'])->name('categories_list');
Route::get('/categories/{id}', 'ArticleController@showByCategory')->name('articles_by_category');
Route::get('/tag/{id}', 'ArticleController@showByTag')->name('articles_by_tag');

Route::get('article/{id}/{slug}', 'ArticleController@detail');

Route::post('/search', 'ArticleController@search')->name('search');

//dd(Route::courentRouteName());
Route::get('/{slug?}', function ($slug = null){
    $seoUrl = \App\SeoUrl::where('slug', '=', $slug)->first();
    if ($seoUrl) {
        $request = \Illuminate\Http\Request::create($seoUrl->URL, 'GET');
        return Route::dispatch($request);
    } else {
        abort('404');
    }
});

resources/views/admin/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

    <link href="{{ asset('assets/select-2/css/select2.min.css') }}" rel="stylesheet" />


    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-secondary shadow-sm">
             <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
{{--                    {{ config('app.name', 'Blog') }}--}}
                    Admin Panel
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">
{{--                        <a class="button" href="{{ route('articles.create') }}">New Article</a>--}}
                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            <div class="d-flex bd-highlight">
                <div class="p-2 bd-highlight">
                    @include('admin.menu')
                </div>
                <div class="p-2 flex-grow-1 bd-highlight">
                    @yield('content')
                </div>
                <div class="p-2 bd-highlight">
                    <p class="text-justify" style="width: 12rem;">
{{--                        TODO: size of tags depending on the quantity you use--}}
{{--                        @if (auth()->guest())--}}
{{--                        @else--}}
{{--                            @foreach($data['tags'] as $tag)--}}
{{--                                <a href="{{ route('articles_by_tag', ['id' => $tag->tag->id]) }}">#{{ $tag->tag->name }}</a>--}}
{{--                            @endforeach--}}
{{--                        @endif--}}
                    </p>
                </div>
            </div>

        </main>
    </div>
</body>
</html>