routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', function () {
//    return view('welcome');
//});
use App\Articles;
use Illuminate\Support\Facades\Input;

Route::get('/testdb', function () {
    $test = new \App\DataResources\CategoriesData();
    $test->getAll();
});


Auth::routes();
Route::get('/', 'HomeController@index')->name('index');

Route::get('/logout', '\App\Http\Controllers\Auth\LoginController@logout');

Route::get('/submit', function () {
    return view('submit');
});

Route::prefix('admin')->middleware('auth')->group(function () {
//    return 'Hello';
    Route::get('', 'Admin\HomeController@index')->name('index');

    Route::get('article/create', 'Admin\ArticlesController@create')->name('create_article');
    Route::get('articles', 'Admin\ArticlesController@index')->name('all_articles');
    Route::get('article/{id}/edit', 'Admin\ArticlesController@edit')->name('edit_article');
    Route::patch('article/{id}', 'Admin\ArticlesController@update')->name('update_article');
    Route::get('article/{id}', 'Admin\ArticlesController@show')->name('show_article');
    Route::delete('article/{id}', 'Admin\ArticlesController@destroy')->name('destroy_article');
    Route::post('article', 'Admin\ArticlesController@store')->name('store_article');

    Route::post('category', 'Admin\CategoriesController@store')->name('store_category');
    Route::get('categories', 'Admin\CategoriesController@index')->name('categories');
    Route::get('category/create', 'Admin\CategoriesController@create')->name('create_category');
    Route::get('category/{id}/edit', 'Admin\CategoriesController@edit')->name('edit_category');
    Route::patch('category/{id}', 'Admin\CategoriesController@update')->name('update_category');
    Route::delete('category/{id}', 'Admin\CategoriesController@destroy')->name('destroy_category');

    Route::get('article/{id}/{slug?}', 'ArticleController@detail');

    Route::delete('img/{gallery}', 'Admin\GalleryController@destroy')->name('destroy_image');
});

Route::resource('articles', 'ArticleController');
Route::get('categories',['uses'=>'CategoryController@manageCategory'])->name('categories_list');
Route::get('/categories/{id}', 'ArticleController@showByCategory')->name('articles_by_category');
Route::get('/tag/{id}', 'ArticleController@showByTag')->name('articles_by_tag');

Route::get('article/{id}/{slug}', 'ArticleController@detail');

Route::post('/search', 'ArticleController@search')->name('search');

//dd(Route::courentRouteName());
Route::get('/{slug?}', function ($slug = null){
    $seoUrl = \App\SeoUrl::where('slug', '=', $slug)->first();
    if ($seoUrl) {
        $request = \Illuminate\Http\Request::create($seoUrl->URL, 'GET');
        return Route::dispatch($request);
    } else {
        abort('404');
    }
});

app/Articles.php
<?php

namespace App;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;

class Articles extends Model
{
    protected $fillable = ['name', 'description', 'short_description', 'author_id', 'category_id', 'active'];

    public function category()
    {
        return $this->hasOne('App\Category', 'id', 'category_id');
    }

    public function author()
    {
        return $this->hasOne('App\User', 'id', 'author_id');
    }

    public function tag()
    {
        return $this->belongsToMany('App\Tag', 'articles_to_tags', 'article_id', 'tag_id')->withTimestamps();
    }

    public function upadted_at()
    {

    }

    public function images()
    {
        return $this->hasMany('App\Gallery', 'article_id', 'id');
    }

    public function getLastUpdateDate()
    {
        return Carbon::parse($this->attributes['created_at'])->diffForHumans();
    }

//    public function getSlugAttribute(): string
//    {
//        return str_slug($this->name);
//    }
//
//    public function getUrlAttribute(): string
//    {
//        return action('Admin\ArticlesController@detail', [$this->id, $this->slug]);
//    }
}

app/Http/Controllers/Admin/ArticlesController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Articles;
use App\Category;
use App\Gallery;
use App\SeoUrl;
use App\Tag;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Storage;
use Intervention\Image\ImageManager;
use Intervention\Image\ImageManagerStatic as Image;
//require 'vendor/autoload.php';

class ArticlesController extends Controller
{
    public function index()
    {
        $articles = Articles::orderBy('updated_at', 'DESC')->paginate(15);
//        dump($articles);
        return view('admin.articles.index', compact('articles'));
    }

    public function edit($id)
    {
        $seoUrl = SeoUrl::where('URL', '/articles/'.$id)->first();
        $gallery = Gallery::where('article_id', $id)->get();
        $activeImage = $gallery->where('status', 'active')->first();

        $allCategories = Category::all();
        $article = Articles::find($id);
        $tags = Tag::orderBy('name')->get();
        return view('admin.articles.edit',
            compact('article', 'allCategories', 'tags' , 'gallery', 'activeImage', 'seoUrl'));
    }

    public function update(Request $request, $id)
    {
        $request->validate([
            'article_name' => 'required',
            'article_short_description' => 'required',
            'article_description' => 'required'
        ]);

        $article = Articles::find($id);

        $article->tag()->detach();
        $tags = $request->input('article_tags');

        if ($tags)
        {
            $new_tags =[];
            foreach ($tags as $key => $tag) {
                if(substr($tag,0,2) == '__') {

                    $add_tag = new Tag();
                    $add_tag->name = substr($tag, 2);
                    $add_tag->save();

                    $new_tags[] = $add_tag->id;
                    unset($tags[$key]);
                }
            }
            $article->tag()->attach($new_tags);
        }
        $images = Gallery::where('article_id', $id)->get();
        foreach($images as $image){
            if($image->id == $request->get('article_file')){
                $image->status = 'active';
                $image->save();
            } else {
                $image->status = '0';
                $image->save();
            }
        }


        $article->tag()->attach($tags);
        $article->name = $request->get('article_name');
        $article->short_description = $request->get('article_short_description');
        $article->description = $request->get('article_description');
        $article->active = (($request->has('article_active'))? '1' : '0');
        $article->category_id = $_POST['article_category'];

        $article->save();
        $store = new Gallery();
        if ($request->file('image')){
            $store->storeImages($request->file('image'), $article);
        }

        if ($request->get('seo_url')) {
            SeoUrl::where('URL' ,'=', route('articles.show', ['article' => $article->id], false))->delete();
            $seoUrl = new SeoUrl();
            $seoUrl->url = route('articles.show', ['article' => $article->id], false);
            $seoUrl->slug = $request->get('seo_url');
            $seoUrl->save();
        }

//        return redirect('articles.show')->with('success', 'Article has been updated');
        return redirect()->route('show_article', compact('article'));
    }

    public function show($id)
    {
        $article = Articles::find($id);
        $gallery = Gallery::where('article_id', $id)->get();
        return view('admin.articles.show', compact('article', 'gallery'));
    }
    public function destroy($id)
    {
        $article = Articles::find($id);
        if (isset($article->images)){
            foreach($article->images as $image) {
                /** @var Gallery $image */
                $image->deleteImage();
            }
        }
        if (isset($article->tag)) {
            $article->tag()->detach();
        }
        $article->delete();
        return redirect()->route('all_articles')->with('success', 'Article has been deleted Successfully');
    }

    public function store(Request $request)
    {
        $request->validate([
            'article_name' => 'required',
            'article_short_description' => 'required',
            'article_description' => 'required',
            'article_category' => 'required'
        ]);

        $tags = $request->input('article_tags');

        $new_tags =[];
        if ($tags){
            foreach ($tags as $key => $tag) {
                if(substr($tag,0,2) == '__') {

                    $add_tag = new Tag();
                    $add_tag->name = substr($tag, 2);
                    $add_tag->save();

                    $new_tags[] = $add_tag->id;
                    unset($tags[$key]);
                }
            }
        }


        $article = new Articles([
            'name' => $request->get('article_name'),
            'short_description' => $request->get('article_short_description'),
            'description' => $request->get('article_description'),
            'active' => (($request->has('article_active'))? '1' : '0'),
            'author_id' => Auth::user()->getAuthIdentifier(),
            'category_id' => $_POST['article_category']
        ]);


        $article->save();
        $article->tag()->attach($tags);
        $article->tag()->attach($new_tags);

        $store = new Gallery();
        if ($request->file('image')){
            $store->storeImages($request->file('image'), $article);
        }

        return redirect()->route('show_article', compact('article'));
    }

    public function create()
    {
        $tags = Tag::orderBy('name')->get();
        $allCategories = Category::all();
        return view('admin.articles.create', compact('allCategories', 'tags'));
    }

//    public function detail($id)
//    {
//        return view('admin.articles.show')->withArticle(Articles::findOrFail($id));
//    }
}

app/Http/Controllers/ArticleController.php
<?php

namespace App\Http\Controllers;

use App\Articles;
use App\ArticlesToTags;
use App\Category;
use App\DataResources\ArticlesData;
use App\DataResources\CategoriesData;
use App\DataResources\GalleryData;
use App\DataResources\TagsData;
use App\Gallery;
use App\Tag;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class ArticleController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        dd('11');
        $articles = Articles::orderBy('created_at', 'DESC')->paginate(15);
        return view('home', compact('articles'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
//        $tags = Tag::orderBy('name')->get();
        $tagsData = new TagsData();
        $tags = $tagsData->getByName();
        $allCategories = Category::all();
        return view('articles.create', compact('allCategories', 'tags'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'article_name' => 'required',
            'article_short_description' => 'required',
            'article_description' => 'required',
            'article_category' => 'required'
        ]);

        $tags = $request->input('article_tags');

        $article = new Articles([
            'name' => $request->get('article_name'),
            'short_description' => $request->get('article_short_description'),
            'description' => $request->get('article_description'),
            'author_id' => Auth::user()->getAuthIdentifier(),
            'category_id' => $_POST['article_category']
        ]);

        $article->save();
        $article->tag()->attach($tags);
        return redirect('/articles')->with('success', 'Article has been added');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {

//        $image = Gallery::where('article_id', '=', $id)->where('status', '=', 'active')->first();
        $imageData = new GalleryData();
        $image = $imageData->getActiveImage($id);
        $gallery = Gallery::where('article_id', $id)->get();
//        dd($image);
//        dd($image->file_name);
//        $article = Articles::find($id);
        $articlesData = new ArticlesData();
        $article = $articlesData->getOne($id);
        $tagsData = new TagsData();
        $tags = collect($tagsData->getByArticle($id));
        return view('articles.show', compact('article', 'image', 'tags', 'gallery'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $allCategories = Category::all();
//        $categoryData = new CategoriesData();
//        $allCategories = collect($categoryData->getAll());
//        $article = Articles::find($id);
        $articlesData = new ArticlesData();
        $article = $articlesData->getOne($id);

        $tagsData = new TagsData();
        $article_tags = collect($tagsData->getByArticle($id));

        $tagsData = new TagsData();
        $tags = $tagsData->getByName();

        return view('articles.edit', compact('article', 'allCategories', 'tags', 'article_tags'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'article_name' => 'required',
            'article_short_description' => 'required',
            'article_description' => 'required'
        ]);

        $article = Articles::find($id);

        $article->tag()->detach();

        $tags = $request->input('article_tags');
        $article->tag()->attach($tags);
        $article->name = $request->get('article_name');
        $article->short_description = $request->get('article_short_description');
        $article->description = $request->get('article_description');
        $article->category_id = $_POST['article_category'];

        $article->save();
        return redirect()->route('articles.show', compact('article'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $article = Articles::find($id);
        $article->tag()->detach();
        $article->delete();
        return redirect('/articles')->with('success', 'Article has been deleted Successfully');
    }
//TODO move from CategoryController
    public function showByCategory($id)
    {
        $cat = new Category();
        $ids = array_unique($cat->getChildsIds($id));

        $articles = Articles::whereIn('category_id', $ids)->where('active', '=', '1')->orderBy('updated_at', 'DESC')->paginate(10);

//        dd($articles);
        return view('articles', compact('articles'));
    }
//TODO Move from
    public function showByTag($id)
    {
//        dd(1111);
        $articles = Articles::whereHas('tag', function ($q) use($id) {
            $q->where('tag_id', $id);
        })->orderBy('updated_at', 'DESC')->paginate(10);
        return view('articles', compact('articles'));
    }

    public function search(Request $request)
    {
        $q = $request->get('q');
        $articles = Articles::where('name','LIKE','%'.$q.'%')->orWhere('short_description','LIKE','%'.$q.'%')->paginate(10);
        if(count($articles) > 0)
            return view('search_home', compact('articles'));
        else return view ('welcome')->withMessage('No Details found. Try to search again !');
    }
}

resources/views/articles/article_card.blade.php
<div class="card m-5 p-5">
    <div class="d-flex flex-column flex-lg-row flex-xl-row">
        <div class="col-lg-3 col-md-12 flex-grow-1">
            @foreach($article->images as $image)
                @if($image->status == 'active')
                    <img class="card-img img-circle" src="{{ asset('thumbnail/' . $image->file_name . '.' . $image->file_type) }}" alt="No main img">
                @endif
            @endforeach
        </div>
        <div class="col-lg-9 col-md-12 flex-grow-1">
            <div class="card-body">
                <a class="card-link" href="{{ url('/articles/'.$article->id) }}">
                    <h1 class="card-title font-3rem font-weight-bold">{{ $article->name }}</h1>
                </a>
                <p class="card-text"><small class="h3 text-muted">{{ $article->getLastUpdateDate() }}</small>
                    <small class="font-weight-bold h3">{{ $article->category->name }}</small>
                    <small class="text-muted h3" >{{ rand(1, 50) }} Comments</small>
                </p>
                <p class="card-text h2 poppins">{{ $article->short_description }}</p>
                <a class="card-link h2 font-blue" href="{{ url('/articles/'.$article->id) }}">Read more</a>

            </div>
        </div>
    </div>
</div>

resources/views/articles/create.blade.php
@extends('layouts.app')

@section('content')
    <script src="https://cdn.ckeditor.com/ckeditor5/12.3.0/classic/ckeditor.js"></script>
    <div class="card uper" xmlns="http://www.w3.org/1999/html">
        <div class="card-header">
            Add Article
        </div>
        <div class="card-body">
            @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div><br />
            @endif
            <form method="post" action="{{ route('articles.store') }}">
                <div class="form-group">
                    @csrf
                    <label for="article_name">Title:</label>
                    <input type="text" class="form-control" name="article_name"/>
                </div>
                <div class="form-group">
                    <label for="article_short_description">Short description:</label>
                    <input type="text" class="form-control" name="article_short_description"/>
                </div>
                <div class="form-group">
                    <label for="article_description">Description:</label>
                    <textarea name="article_description" id="editor"></textarea>
                </div>
                <div class="form-group">
                    <label for="article_category">Category:</label>
                    <select class="custom-select" name="article_category" id="article_category">
                        @foreach($allCategories as $category)
                            <option value="{{ $category->id }}">{{ $category->name }}</option>
                        @endforeach
                    </select>
                </div>
                <div class="form-group">
                    <label for="article_tags">Tags:</label>
                    <select class="custom-select" name="article_tags[]" id="article_tags" multiple>
                        @foreach($tags as $tag)
                            <option value="{{ $tag->id }}">#{{ $tag->name }}</option>
                        @endforeach
                    </select>
                </div>
                <button type="submit" class="btn btn-primary">Add</button>
            </form>
        </div>
        <script>
            $(document).ready(function () {
                ClassicEditor
                    .create( document.querySelector( '#editor' ) )
                    .catch( error => {
                        console.error( error );
                    } );
            })
        </script>
    </div>
@endsection

resources/views/articles/edit.blade.php
@extends('layouts.app')

@section('content')
    <script src="https://cdn.ckeditor.com/ckeditor5/12.3.0/classic/ckeditor.js"></script>
    <div class="card uper">
        <div class="card-header">
            Edit Article
        </div>
        <div class="card-body">
            @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div><br />
            @endif
            <form method="post" action="{{ route('articles.update', $article->article_id) }}">
                @method('PATCH')
                @csrf
                <div class="form-group">
                    <label for="article_name">Title:</label>
                    <input type="text" class="form-control" name="article_name" value="{{ $article->name }}" />
                </div>
                <div class="form-group">
                    <label for="article_short_description">Short description:</label>
                    <input type="text" class="form-control" name="article_short_description" value="{{ $article->short_description }}" />
                </div>
                <div class="form-group">
                    <label for="article_description">Description:</label>
                    <textarea name="article_description" id="editor">{{ $article->description }}</textarea>
                </div>
                <div class="form-group">
                    <label for="article_category">Category:</label>
                    <select class="custom-select" name="article_category" id="article_category">
                        @foreach($allCategories as $category)
                            <option value="{{ $category->id }}"
                                    @if($category->id == $article->category->id)
                                        selected
                                    @endif>
                                {{ $category->name }}
                            </option>
                        @endforeach
                    </select>
                </div>
                <div class="form-group">
                    <label for="article_tags">Tags:</label>
                    <select class="custom-select" name="article_tags[]" id="article_tags" multiple>
                        @foreach($tags as $tag)
                            <option value="{{ $tag->id }}"
                                @foreach($article_tags as $atag)
                                    @if($atag->tag_id == $tag->id)
                                        selected
                                    @endif
                                @endforeach
                            >#{{ $tag->name }}</option>
                        @endforeach
                    </select>
                </div>
                <button type="submit" class="btn btn-primary">Update</button>
            </form>
        </div>
        <script>
            $(document).ready(function () {
                ClassicEditor
                    .create( document.querySelector( '#editor' ) )
                    .catch( error => {
                        console.error( error );
                    } );
            })
        </script>
    </div>
@endsection

resources/views/articles/popular_articles.blade.php
<h1 class="display-4 mt-5 pt-5 poppins">Popular articles</h1>
<br>
@foreach($data['popularArticles'] as $popArt)
    <div>
        <div class="card popular-articles-card mb-3" style="max-width: 540px;">
            <div class="row no-gutters">
                <div class="col-md-4">
                    @foreach($popArt->images as $image)
                        @if($image->status == 'active')
                            <img class="card-img popular-article-image" src="{{ asset('thumbnail/' . $image->file_name . '.' . $image->file_type) }}" alt="No main img" >
                        @endif
                    @endforeach
                </div>
                <div class="col-md-8">
                    <div class="card-body">
                        <a href="{{ url('/articles/'.$popArt->id) }}"><h2>{{$popArt->name}}</h2></a>
                        <p class="card-text popular-article-text"><small class="text-muted h4">
                                <i class="glyphicon glyphicon-calendar"></i>
                                {{ $popArt->getLastUpdateDate() }}
                                <i class="glyphicon glyphicon-user"></i>
                                {{ $popArt->author->name }}</small></p>
                        <p class="card-text popular-article-text"><small class="text-muted"><i class="glyphicon glyphicon-comment"></i> {{ rand(1,50) }}</small></p>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endforeach

resources/views/articles/show.blade.php
@extends('layouts.app')
@section('navbarOff')
@endsection
@section('content')
    <div class="p-2 col-lg-2 col-xl-2 offset-lg-1 offset-xl-1 offset-0 col-12 flex-grow-1 bd-highlight mt-auto mb-auto article-content">
        <div class="d-flex flex-column">
            <div class="p-2 bd-highlight">
                <h1 class="mb-5">Gallery</h1>
            </div>
            @foreach($gallery as $img)
                <div class="p-2 bd-highlight">
                    <img class="img-circle mb-5 mt-5" src="{{ asset('thumbnail/' . $img->file_name . '.' . $img->file_type) }}" alt="No main img">
                </div>
            @endforeach
        </div>
    </div>
    <div class="col-1 border-left d-none d-lg-block d-xl-block"></div>
    <div class="p-2 col-lg-5 col-xl-5 col-12 flex-grow-1 bd-highlight ml-auto mr-5 article-content">
        <h1 class="display-3">{{ $article->article_name }}</h1>
        @if($image)
            <img src="{{ asset('thumbnail/' . $image->file_name . '.' . $image->file_type) }}" alt="No main img">
        @endif
        <p>{!! $article->description !!}</p>
        <p>
            @foreach($tags as $tag)
                <small><a class="" href="{{ route('articles_by_tag', ['id' => $tag->tag_id]) }}">{{ $tag->name }}</a></small>
            @endforeach
        </p>
{{--            <a href="{{ action('ArticleController@edit', $article->article_id) }}" class="btn btn-secondary">Edit</a>--}}
{{--            <form action="{{ action('ArticleController@destroy', $article->article_id) }}" method="POST">--}}
{{--                <input type="hidden" name="_method" value="DELETE">--}}
{{--                <input type="hidden" name="_token" value="{{ csrf_token() }}">--}}
{{--                <input type="submit" class="btn btn-danger" value="Delete"/>--}}
{{--            </form>--}}
    </div>
@endsection